### ISSUE TITLE
Rock Paper Scissors 

### ISSUE THREAD

**Issue by sidharthbh8** [Open-Source-you/Hackotberfest2022#65]
Made a rock paper scissors game using HTML5 CSS3 & JS.
Hey @Open-Source-you  can you assign me this issue.

**Comment by Open-Source-you** [comment]
> Made a rock paper scissors game using HTML5 CSS3 & JS. Hey @Open-Source-you can you assign me this issue.

okay

**Comment by Prashant2001k** [comment]
can you assign me this issue

**Comment by Open-Source-you** [comment]
> can you assign me this issue

okay, i will assign you this issue

**Comment by imNilabja** [comment]
I would like to do this task, can you assign me

**Comment by Kaushals112** [comment]
i can do this task sir.can you assign me please.

**Comment by vcvedika** [comment]
Can you assign this issue to me?

**Comment by Open-Source-you** [comment]
> Can you please assign this issue 
okay i will assign you this issue.

**Comment by sidharthbh8** [comment]
hey @Open-Source-you isn't this PR already merged

**Comment by Open-Source-you** [comment]
> hey @Open-Source-you isn't this PR already merged

our PR code quality is very bad

**Comment by sidharthbh8** [comment]
> > hey @Open-Source-you isn't this PR already merged
> 
> our PR code quality is very bad

lol you mentioned in the readme that its for beginners

**Comment by Open-Source-you** [comment]
> > > hey @Open-Source-you isn't this PR already merged
> > 
> > 
> > our PR code quality is very bad
> 
> lol you mentioned in the readme that its for beginners

I did not mention that upload the code directly,Had to do it from git base

**Comment by Open-Source-you** [comment]
I did not know you are such a noobda
